# Generated by Django 4.0.6 on 2022-07-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('rasmi', models.ImageField(upload_to='media/')),
                ('tarkibi', models.TextField()),
                ('qollanilishi', models.TextField()),
                ('foydalanish_tartibi', models.TextField()),
            ],
        ),
    ]
