# Generated by Django 4.0.6 on 2022-07-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dori',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='dori',
            name='rasmi',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Dori Rasmlari'),
        ),
    ]
