# Generated by Django 4.0.6 on 2022-08-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentimagemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='comments', verbose_name='Comments Image'),
        ),
    ]
