# Generated by Django 4.0.6 on 2022-07-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dori_is_active_alter_dori_rasmi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dori',
            options={'verbose_name': 'Dori', 'verbose_name_plural': 'Dori'},
        ),
        migrations.AlterField(
            model_name='dori',
            name='rasmi',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Dori Rasmlari'),
        ),
    ]
