# Generated by Django 4.1 on 2022-08-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_commentimagemodel_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="YoutubeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.URLField()),
            ],
        ),
    ]
