# Generated by Django 4.0.6 on 2022-07-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dori_options_alter_dori_rasmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dori',
            name='is_active',
        ),
    ]
