# Generated by Django 4.0.6 on 2022-07-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_dori_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dori',
            name='rasmi',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Dori Rasmlari'),
        ),
    ]
