# Generated by Django 4.0.6 on 2022-08-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_emaimodel_facebookmodel_telefonmodel_twittermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaimodel',
            name='name',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='facebookmodel',
            name='name',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='telefonmodel',
            name='name',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='twittermodel',
            name='name',
            field=models.URLField(max_length=255),
        ),
    ]
