# Generated by Django 4.0.6 on 2022-08-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_emaimodel_name_alter_facebookmodel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('avatar', models.ImageField(upload_to='staff/')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='emaimodel',
            name='name',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='facebookmodel',
            name='name',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='telefonmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='twittermodel',
            name='name',
            field=models.URLField(),
        ),
    ]
