# Generated by Django 4.0.6 on 2022-08-04 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_instagrammodel_map_order_staff_telegrammodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmaiModel',
            new_name='EmailModel',
        ),
    ]
