# Generated by Django 4.0.6 on 2022-08-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_emaimodel_emailmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='kasbi',
            field=models.CharField(default='Doktor', max_length=255),
        ),
    ]
