# Generated by Django 4.0.6 on 2022-08-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_staff_kasbi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='linkedin',
            new_name='telegram',
        ),
        migrations.AddField(
            model_name='staff',
            name='telefon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
