# Generated by Django 4.0.6 on 2022-08-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_linkedin_staff_telegram_staff_telefon'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('rasmlar', models.ImageField(blank=True, null=True, upload_to='website/', verbose_name='Website')),
            ],
        ),
    ]
