# Generated by Django 4.0.6 on 2022-08-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_websitetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
