# Generated by Django 4.0.6 on 2022-08-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_telegrammodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitetext',
            old_name='rasmlar',
            new_name='photos',
        ),
        migrations.AlterField(
            model_name='telegrammodel',
            name='name',
            field=models.URLField(),
        ),
    ]
