# Generated by Django 4.0.6 on 2022-08-06 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_rasmlar_websitetext_photos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Feedback',
        ),
    ]
