# Generated by Django 4.0.6 on 2022-08-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_order_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='websitetext',
            name='photos',
        ),
        migrations.CreateModel(
            name='CommentImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comments')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commentmodel')),
            ],
        ),
    ]
