# Generated by Django 4.0.6 on 2022-08-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_commentmodel_remove_websitetext_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentimagemodel',
            name='comment',
        ),
    ]
